### PR TITLE
[fix] head elements in a list element are omitted

### LINKED ISSUE #118: List headers are not rendered in epub
When you generate an epub, a `head` element inside  a`list` element should be rendered as the list's header, however, it will be omitted

When you use this code to generate an epub:

```xml
<list>
    <head>head</head>
    <item>item 1</item>
    <item>item 2</item>
    <item>item 3</item>
</list>
```

**Actual result:**
```html
<ul class="tei-list2">
    <li class="tei-item">item 1</li>
    <li class="tei-item">item 2</li>
    <li class="tei-item">item 3</li>
</ul>
```

**Expected result:**
```html
<ul class="tei-list2">
    <li class="tei-head5">head</li>
    <li class="tei-item">item 1</li>
    <li class="tei-item">item 2</li>
    <li class="tei-item">item 3</li>
</ul>
```

### PR DESCRIPTION
**Pull request by ccheraa**
Currently only `item` elements in a `list` are rendered, this will include `head` elements too

fixes #118

This open source contribution to the tei-publisher-app project was commissioned by the Office of the Historian, U.S. Department of State, https://history.state.gov/.

### CODE REVIEW

**Review by duncdrum — CHANGES_REQUESTED** [review]
Hi Charaf,
thank you for the PR, but the `tei_simplePrint.odd` is directly provided by the TEI folks, and should not be modified here. It is also the base for most of the tei-publisher odds. 

Instead of making the change here, you can achieve the desired output by using your own odd customization and recompiling odds. Once you have everything you need from this PR, can you please close it.

**Comment by ccheraa** [comment]
I still think this should be fixed, if you look at the ODD, it says the `head` element should be rendered as a `block` if its parent is a `list` element:
https://github.com/eeditiones/tei-publisher-app/blob/3d38420603d672c37bb08259f71253e2125b2f4c/odd/tei_simplePrint.odd#L4516-L4526

And it says that only `item` elements should be rendered under a `list` element:
https://github.com/eeditiones/tei-publisher-app/blob/3d38420603d672c37bb08259f71253e2125b2f4c/odd/tei_simplePrint.odd#L4580-L4587

Which means we will never have a `list` element that's a parent of a `head` element, which makes the first mentioned model irrelevant.

So if omitting `head` elements is intended, then the model about rendering `head` elements under `list` elements should be removed.

**Comment by duncdrum** [comment]
all good points, but such changes need to be implemented by the tei folks who are the authors of the `tei_simplePrint.odd`. PRs need to go to them, tei-publisher is only a user library that includes the ODD provided by the TEI council.

**Comment by wolfgangmm** [comment]
`tei_simplePrint.odd` certainly is in need for a review, but this needs coordination and for the time being, we use it as is. `tei-publisher.odd` extends it and corrects the obvious mistakes. So your change should go there.

**Pull request closed without merging**
