### PR TITLE
Adopt community XQuery file extension convention

### PR DESCRIPTION
**Pull request by joewiz**
- main modules: .xq
- library modules: .xqm

Requires https://github.com/eeditiones/tei-publisher-lib/pull/7 and https://github.com/eeditiones/tei-publisher-components/pull/92.

### CODE REVIEW

**Comment by joewiz** [comment]
For the motivation, I'll quote from my post at https://gitlab.existsolutions.com/tei-publisher/tei-publisher-app/-/issues/152#note_8478:

> Might I also suggest taking the opportunity during a cleanup effort in this app to apply consistent naming for XQuery file extensions? We currently mix `.xq`, `.xql`, and `.xqm` in this and generated apps. While arbitrary, there is an important difference between main modules and library modules for developers, and rather than continuing to mix conventions, we could demonstrate the use of best practices. The community convention (most recently discussed at https://github.com/eXist-db/documentation/issues/258) is as follows:
> 
> - `.xq` for main modules 
> 
> - `.xqm` for library modules
> 
> The only exception would be controller.xql, which is hard coded in the eXist core. This is, of course, a main module.
> 
> I'd be happy to take this on so that it's not a drain on the other important cleanup tasks defined above - just let me know.

And in [a followup post](https://gitlab.existsolutions.com/tei-publisher/tei-publisher-app/-/issues/152#note_11201) in the same thread:

> I'll provide a little more background. I like to root my own thinking on the topic in the spec, describe what leeway the spec gives us, and then describe community conventions: 
> 
> The XQuery spec is quite spare on the topic of [file extensions](https://www.w3.org/TR/xquery-31/#id-file-extensions):
> 
> > The most common file extensions in use for XQuery are `.xq` and `.xquery`.
> 
> In contrast, the spec provides clear definitions for [main modules](https://www.w3.org/TR/xquery-31/#GLdt-main-module) vs. [library modules](https://www.w3.org/TR/xquery-31/#GLdt-library-module):
> 
> > A module that does not contain a Query Body is called a **library module**. A library module consists of a module declaration followed by a Prolog.
> 
> > A **main module** consists of a Prolog followed by a Query Body.
> 
> From this I conclude the following:
> 
> 1. The spec doesn't mandate a particular file extension, or system of file extensions, for XQuery. It merely says that `.xq` and `.xquery` are the most common.
> 2. The spec doesn't say whether communities should adopt a single file extension for XQuery files extension. A community is free to arbitrarily intermix `.xq`, `.xquery` (oXygen's default for XQuery files), `.xqy` (used commonly in the MarkLogic community), or `.xql` or `.xqm` (both used fairly interchangeably in many eXist community projects), or `.txt` for that matter. 
> 3. The spec doesn't discuss whether communities should use file extensions to distinguish between main modules and library modules. We could simply use `.xq` for all XQuery files, for example. But if a community does want to use file extensions to make this distinction, it would make sense to select a mnemonic device or rationale for the choice, document the choice, and stick with it & enforce it:
>     1. `.xq` for main modules, `.xql` for **L**ibrary modules
>     2. `.xq` for main modules, `.xqm` for library **M**odules
>     3. `.xqm` for **M**ain modules, `.xql` for **L**ibrary modules
>     4. `.xql` for main modules (or XQuery **L**anguage), `.xqm` for library **M**odules
>     5. (For extra points, use `.xq` for all modules! Just look inside the file, and if you see a "module" declaration, you know if it's a **L**ibrary module; if you don't see one, you'll know it's just a **M**ain module, !!@&$#!)
> 
> It seems like TEI Publisher has selected option 4 here.  That's fine.
> 
> However, the eXist book recommends option 2, and this was the result of fairly extensive discussions started in this 2009 exist-open thread, prompted by a question about the proliferation of XQuery file extensions: https://sourceforge.net/p/exist/mailman/exist-open/thread/2e0234190911192025v117160a7sf904bd67a7101c06%40mail.gmail.com/. This thread is what led the eXist book to adopt 2 as the recommendation. This decision was in part based on BaseX's use of this convention, and the agreement of everyone who weighed in from the community. That's the closest thing we have to an eXist community convention. We've never enforced it on any community apps (despite https://github.com/eXist-db/documentation/issues/258 having been open for over a year), so you'll still see many apps that freely mix file extensions even in a single app. Just because we have a good, if loosely enforced convention, doesn't mean TEI Publisher needs to follow it. I'd welcome you to do so, but do whatever works and makes sense.
> 
> For reference, I should also mention that raised the question again in 2013 in the xquery-talk list, where the discussion included more than just eXist folks: http://x-query.com/pipermail/talk/2013-January/004030.html.

Since that thread 2-3 years ago, the XQuery for Humanists book came out - adding its endorsement of the `.xq` and `.xqm` convention. Also, with eXist 6.0.0, now supports `controller.xq` and gives it higher precedence than `controller.xql` - see https://github.com/eXist-db/exist/issues/3739. The standard app generator for eXist, generator-exist, now generates all apps using this convention as of its v6.0.0 release - https://github.com/eXist-db/generator-exist/issues/614. eXide 

Thus, for pedagogical and practical purposes, adopting this convention consistently will aid new and longstanding contributors to TEI Publisher instantly understand the nature of each XQuery module by glancing at the file extension. As an example of one such user, I constantly find myself guessing whether an .xql file is a library module or main module and find it frustrating that I have to manually examine the file to know for sure. 

This PR already updates the documentation where relevant, and I would be happy to contribute to the "updating" article in the documentation for the release where this is included - conceivably, the forthcoming TEI Publisher 8 release. I imaging that the lib and components repos might also need major releases. But this puts all of the projects on an even more solid foundation, so I would argue that it is worthy of a major release.

Comments welcome!

**Comment by tuurma** [comment]
Hi @joewiz, while agreeing in principle re naming conventions, after some discussions we determined that disturbance to existing Publisher editions and potential for confusion for users is too great to justify the change. Therefore I will close this PR, nevertheless many thanks for your work and consideration that went into this proposal.

**Comment by joewiz** [comment]
@tuurma Thanks for your consideration of the PR. While I agree the proposed shift would be painful for current users migrating to a new version, the pain would have been limited to one upgrade cycle, and it would have relieved confusion and make it easier for new and existing users to understand the project and contribute to it. The continued proliferation of inconsistent file extensions (not to mention mismatches between module names, namespace prefixes, and URIs) will continue to impose its own pain - a type of technical debt. I'm sure you've considered this in the calculus, and I fully accept the decision, but I thought it would be worth articulating the trade-off. There may come a day when reworking the naming is worth it. 

Also, it might be worth adopting a consistent naming convention for new code. A statement to the effect of, say: 

> As of 2023-03-16, new XQuery modules contributed to the TEI Publisher repository should use the `.xq` file extension for main modules and `.xqm` for library modules. Module namespace URIs should begin with a `http://teipublisher.com/ns` prefix and a suffix that matches the filename, and a namespace prefix that either matches the filename or is a logical abbreviation/truncation thereof. For example, ... Existing code that does not conform to this convention should not be changed, for backwards compatibility.

**Comment by tuurma** [comment]
@joewiz I agree that we may want to rework the naming at some point, perhaps already for the 9 release if, as it seems to me now, it may include further breaking changes.

Meanwhile, would you rather keep this PR opened or, as I would actually prefer, open an issue about the conventions you mention, i.e. not only module extensions but also prefixes and URIs?

**Comment by joewiz** [comment]
@tuurma I like your idea to open a new issue. I'll aim to do so ASAP.

**Pull request closed without merging**
