### PR TITLE
Create a well-defined API for all server-side services

### PR DESCRIPTION
**Pull request by wolfgangmm**
This will become the next iteration of TEI Publisher. While the client-side has been addressed with version 6 by moving all UI components into an independent package, we're now refactoring the server-side:

* all server-side services of TEI Publisher are driven by a single specification following the Open API standard: [see api.json](https://github.com/eeditiones/tei-publisher-app/blob/59ae871d43851926118168f2aae205def8505a1e/modules/lib/api.json)
* on the server a new package, [oas-router](https://github.com/eeditiones/oas-router), reads the API specification and uses it to map HTTP requests to the XQuery functions which do the actual heavy-lifting

Benefits:

* TEI Publisher gets a well-defined, clear API which you can use to write software against publisher without being forced to use its client side components
* every API operation can be tested and compared against the specification, making sure that e.g. parameter and response types correspond exactly to the definition
* by embracing Open API, all the existing tools for documentation, code generation etc. can be reused
* the code will become more lean and upgrades will become much easier

Todo:

- [x] transformation to PDF via FO
- [x] pb-download needs to be adjusted
- [x] implement search interface
- [x] calls to facets.xql
- [x] ODD editor AJAX calls (see editor.xql)
    - [x] open ODD as JSON
    - [x] retrieve single elementSpec as JSON
    - [X] lint XQuery expression
    - [X] save modified ODD
- [x] check error handling if XQuery module code has bad syntax
- [ ] pb-browse-docs form controls
- [x] pb-autocomplete
- [x] app-download.xql
- [x] DTS 
- [x] app-generate.xql
- [x] backwards compatibility for components: TEI Publisher 7 should report API version 1.0, for other version 0.9 is assumed by default
- [x] image links in pb-browse-docs broken
- [x] allow user-defined oapi definitions to be added on top of the default `api.json`
- [x] link to ODD editor in administration menu doesn't work
- [x] make sure generated apps work - needs sync with latest changes

### CODE REVIEW

**Comment by joewiz** [comment]
@wolfgangmm Looking at [`deploy:download-app()`](https://github.com/eeditiones/tei-publisher-app/blob/55ef827d8cc929466566e0f38df24cd858e2c17d/modules/lib/api/generate.xql#L469-L474) and [`deploy:package()`](https://github.com/eeditiones/tei-publisher-app/blob/55ef827d8cc929466566e0f38df24cd858e2c17d/modules/lib/api/generate.xql#L436-L441), I believe that tei-publisher-app will suffer from the same bug reported by @djbpitt in https://github.com/eXist-db/eXide/issues/271. Namely, compression:zip implicitly accepts the eXist serializer's default of `indent=yes` on XML sources, which can introduce whitespace into documents and thus mangle their contents. Short of adding a serialization options parameter to the `compression:zip()` function, tei-publisher-app could adopt eXide's fix: constructing entries and serializing the XML with parameters `indent=no` (and `expand-xincludes=no`, which is also eXide's default since https://github.com/eXist-db/eXide/issues/90).

**Comment by wolfgangmm** [comment]
Thanks for the hint @joewiz! I have now chosen a slightly different approach in https://github.com/eeditiones/tei-publisher-app/commit/d942b0ab4a27295caba4f383201c6f463092cabb#diff-139838d8bd1e9f9bc5d8b3bafdf62b9bR440, using `fn:serialize` to serialize the XML.

**Comment by joewiz** [comment]
@wolfgangmm This looks good! I had to take the other route because I wanted to control the `expand-xincludes` parameter, which is not available via `fn:serialize`. Indeed, the docs [say this](https://exist-db.org/exist/apps/doc/xquery#serialization) (my emphasis added):

> Most of the legacy serialization parameters have an equivalent in the standard serialization parameters, but others are truly specific to eXist-db, and are _thus accessible only using the legacy serialization approach_.

To check, I wrote the following text, which expands the xinclude despite the directive not to:

```xquery
serialize(
    <foo xmlns:xi="http://www.w3.org/2001/XInclude">
        <xi:include href="/db/apps/eXide/repo.xml"/>
    </foo>, 
    map { "expand-xincludes": false() }
)
```

I think avoiding xinclude expansions follows the same principle: that documents uploaded to eXist should be serialized the same way when downloading them. Perhaps some users would like the option to expand them (and this option could be exposed in the UI for generating xars). But as for a default, I think the more conservative approach is to default to `expand-xincludes=no`.

**Comment by joewiz** [comment]
I should add that the reason I had to resort to `util:declare-option()` followed by `doc()` in eXide's handing of xar generation is that this is the _only_ method for setting eXist-specific serialization parameters following the removal of `util:serialize()` in eXist 5. See https://github.com/eXist-db/exist/issues/2394 for some ideas for exposing these eXist-specific serialization parameters to standard methods in eXist 5.

**Pull request merged**
